# Introduction to statsmodels

## BrainHack Global 2018 Leipzig  

statsmodels is a Python module that provides classes and functions for the estimation of many different statistical models, as well as for conducting statistical tests, and statistical data exploration.

In [1]:
import numpy as np
import statsmodels.api as sm # regular api
import statsmodels.formula.api as smf # R-style formula augmented api

/home/michael/.local/lib/python3.5/site-packages/statsmodels/compat/pandas.py:56: FutureWarning: The pandas.core.datetools module is deprecated and will be removed in a future version. Please use the pandas.tseries module instead.
  from pandas.core import datetools


In [2]:
# Load data
dat = sm.datasets.get_rdataset("Guerry", "HistData").data

In [3]:
type(dat)

pandas.core.frame.DataFrame

In [4]:
dat.shape

(86, 23)

In [5]:
dat.index

RangeIndex(start=0, stop=86, step=1)

In [6]:
dat.columns

Index(['dept', 'Region', 'Department', 'Crime_pers', 'Crime_prop', 'Literacy',
       'Donations', 'Infants', 'Suicides', 'MainCity', 'Wealth', 'Commerce',
       'Clergy', 'Crime_parents', 'Infanticide', 'Donation_clergy', 'Lottery',
       'Desertion', 'Instruction', 'Prostitutes', 'Distance', 'Area',
       'Pop1831'],
      dtype='object')

In [7]:
dat.describe()

dept    Crime_pers    Crime_prop   Literacy     Donations  \
count   86.000000     86.000000     86.000000  86.000000     86.000000   
mean    46.883721  19754.406977   7843.058140  39.255814   7075.546512   
std     30.426157   7504.703073   3051.352839  17.364051   5834.595216   
min      1.000000   2199.000000   1368.000000  12.000000   1246.000000   
25%     24.250000  14156.250000   5933.000000  25.000000   3446.750000   
50%     45.500000  18748.500000   7595.000000  38.000000   5020.000000   
75%     66.750000  25937.500000   9182.250000  51.750000   9446.750000   
max    200.000000  37014.000000  20235.000000  74.000000  37015.000000   

            Infants       Suicides     Wealth   Commerce     Clergy  \
count     86.000000      86.000000  86.000000  86.000000  86.000000   
mean   19049.906977   36522.604651  43.500000  42.802326  43.430233   
std     8820.233546   31312.532649  24.969982  25.028370  24.999549   
min     2660.000000    3460.000000   1.000000   1.000000   1.000000   
25%    14299.750000   15463.000000  22.250000  21.250000  22.250000   
50%    17141.500000   26743.500000  43.500000  42.500000  43.500000   
75%    22682.250000   44057.500000  64.750000  63.750000  64.750000   
max    62486.000000  163241.000000  86.000000  86.000000  86.000000   

       Crime_parents  Infanticide  Donation_clergy    Lottery  Desertion  \
count      86.000000    86.000000        86.000000  86.000000  86.000000   
mean       43.500000    43.511628        43.500000  43.500000  43.500000   
std        24.969982    24.948297        24.969982  24.969982  24.969982   
min         1.000000     1.000000         1.000000   1.000000   1.000000   
25%        22.250000    22.250000        22.250000  22.250000  22.250000   
50%        43.500000    43.500000        43.500000  43.500000  43.500000   
75%        64.750000    64.750000        64.750000  64.750000  64.750000   
max        86.000000    86.000000        86.000000  86.000000  86.000000   

       Instruction  Prostitutes    Distance          Area     Pop1831  
count    86.000000    86.000000   86.000000     86.000000   86.000000  
mean     43.127907   141.872093  207.953140   6146.988372  378.628721  
std      24.799809   520.969318  109.320837   1398.246620  148.777230  
min       1.000000     0.000000    0.000000    762.000000  129.100000  
25%      23.250000     6.000000  121.383000   5400.750000  283.005000  
50%      41.500000    33.000000  200.616000   6070.500000  346.165000  
75%      64.750000   113.750000  289.670500   6816.500000  444.407500  
max      86.000000  4744.000000  539.213000  10000.000000  989.940000

In [8]:
# Building a desing matrix with Literacy, ln(Pop1831) and a constant
design = np.vstack((np.array(dat['Literacy']), np.log(np.array(dat['Pop1831'])), np.ones(86))).T

In [9]:
design.shape

(86, 3)

In [10]:
# Fit regression model 
results = sm.OLS(np.array(dat['Lottery']), design).fit()

In [11]:
# Inspect the results
print(results.summary())

                            OLS Regression Results                            
Dep. Variable:                      y   R-squared:                       0.348
Model:                            OLS   Adj. R-squared:                  0.333
Method:                 Least Squares   F-statistic:                     22.20
Date:                Fri, 04 May 2018   Prob (F-statistic):           1.90e-08
Time:                        13:12:20   Log-Likelihood:                -379.82
No. Observations:                  86   AIC:                             765.6
Df Residuals:                      83   BIC:                             773.0
Df Model:                           2                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
x1            -0.4889      0.128     -3.832      0.0

In [12]:
results.resid

array([ -4.28111552,  11.89268483,   4.33310509,  14.15428738,
        18.49333749,  19.34635558,  -5.18545491,  10.63946318,
       -17.16226913,  -4.50128015,  33.94273906, -40.59906372,
       -13.75575698,  24.66490891,  15.68850058,  -1.4093396 ,
       -22.44356669,  21.4820131 ,   1.554968  ,  33.62638801,
        24.5650803 ,  32.85520129, -17.96987559,   6.64806247,
        14.94499379,   4.26860396,  -7.02036876, -22.80379617,
       -16.5681693 ,  25.98243394, -25.0649797 , -22.34530592,
         0.19288205,   3.1666575 , -39.95241358, -11.66823101,
         8.1288396 ,  16.85612047, -16.18620796,  -3.34919918,
         3.58889929, -30.04335068, -29.75969329,  20.15852714,
         3.86306657,   7.57468271, -18.68049242,  33.42794816,
       -11.38962699,  17.63168192,   7.50630409,  -3.39057162,
        27.82647646, -17.46837681, -13.66117011,   3.05798305,
        -1.45773319,  10.39062873,  23.28631052,   7.5765857 ,
        14.71649423,   0.29409873,  26.16244145, -61.94

In [13]:
results.params

array([ -0.48892344, -31.31139219, 246.43413487])

In [14]:
np.allclose(np.array(dat['Lottery']) - design.dot(results.params), results.resid )

True

In [15]:
# Fit regression model (using the natural log of one of the regressors)
results2 = smf.ols('Lottery ~ Literacy + np.log(Pop1831)', data=dat).fit()

In [16]:
# Inspect the results
print(results2.summary())

                            OLS Regression Results                            
Dep. Variable:                Lottery   R-squared:                       0.348
Model:                            OLS   Adj. R-squared:                  0.333
Method:                 Least Squares   F-statistic:                     22.20
Date:                Fri, 04 May 2018   Prob (F-statistic):           1.90e-08
Time:                        13:12:21   Log-Likelihood:                -379.82
No. Observations:                  86   AIC:                             765.6
Df Residuals:                      83   BIC:                             773.0
Df Model:                           2                                         
Covariance Type:            nonrobust                                         
                      coef    std err          t      P>|t|      [0.025      0.975]
-----------------------------------------------------------------------------------
Intercept         246.4341     35.233     

In [17]:
results.params

array([ -0.48892344, -31.31139219, 246.43413487])

In [18]:
results2.params

Intercept          246.434135
Literacy            -0.488923
np.log(Pop1831)    -31.311392
dtype: float64

## Formula with the patsy module

patsy is a Python package for describing statistical models (especially linear models, or models that have a linear component) and building design matrices. It is closely inspired by and compatible with the formula mini-language used in R and S.

In [19]:
import patsy as pa

In [20]:
design = pa.dmatrices("dat['Lottery'] ~ dat['Literacy'] + np.log(dat['Pop1831'])")

In [21]:
type(design[0])

patsy.design_info.DesignMatrix

In [22]:
np.asarray(design[1])[:10]

array([[ 1.        , 37.        ,  5.84652548],
       [ 1.        , 51.        ,  6.24027585],
       [ 1.        , 13.        ,  5.69796559],
       [ 1.        , 46.        ,  5.04921478],
       [ 1.        , 69.        ,  4.8605873 ],
       [ 1.        , 27.        ,  5.83109037],
       [ 1.        , 67.        ,  5.66856972],
       [ 1.        , 18.        ,  5.53386368],
       [ 1.        , 59.        ,  5.50679388],
       [ 1.        , 34.        ,  5.59890332]])

In [23]:
np.asarray(design[0])[:10]

array([[41.],
       [38.],
       [66.],
       [80.],
       [79.],
       [70.],
       [31.],
       [75.],
       [28.],
       [50.]])

Checkout https://patsy.readthedocs.io/en/latest/formulas.html for the details of the formula language (higher order relation, operator precedence, etc)

In [24]:
# Non-sensical model to show formula
# a*b --> a + b + a:b
results3 = smf.ols('Lottery ~ (Literacy*Wealth*Donations) - Literacy:Wealth + np.log(Pop1831)', data=dat).fit()

In [25]:
print(results3.summary())

                            OLS Regression Results                            
Dep. Variable:                Lottery   R-squared:                       0.428
Model:                            OLS   Adj. R-squared:                  0.376
Method:                 Least Squares   F-statistic:                     8.322
Date:                Fri, 04 May 2018   Prob (F-statistic):           1.48e-07
Time:                        13:12:21   Log-Likelihood:                -374.26
No. Observations:                  86   AIC:                             764.5
Df Residuals:                      78   BIC:                             784.2
Df Model:                           7                                         
Covariance Type:            nonrobust                                         
                                coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------------------
Intercept             

# Checkout https://www.statsmodels.org/stable/index.html for detailed documentation and exemples on statsmodels